import sys
import csv
import os
import matplotlib.pyplot as plt
import numpy as np

# This script opens a series of .csv files generated by the QQMS website,
#  finds a .csv file corresponding to the same spectrum from another program
#  (such as MOCalc2012, ChimeraX, or Avogadro for Orca) and plots
#  both spectra simultaneously for comparison.


filepath = os.getcwd()
# qmprog = ["gms"]
# qmprog = ["gms", "orc", "ps4"]
qmprog = ["gms", "nwc", "orc", "ps4"]
spectyp = ["ir", "ram", "uvv"]

for qmp in qmprog:
    for spect in spectyp:
        web_rows = []
        oth_rows = []
        web_freqs = []
        web_inten = []
        oth_freqs = []
        oth_inten = []
        csv_web = qmp + "_bzorig_b3lyp_nosmd_" + spect + "_web.csv"
        csv_oth = qmp + "_bzorig_b3lyp_nosmd_" + spect + "_oth.csv"
        csv_tot_web = filepath + "\\" + csv_web
        csv_tot_oth = filepath + "\\" + csv_oth
        if ((os.path.isfile(csv_tot_web)) and (os.path.isfile(csv_tot_oth))):
            with open(csv_tot_web, newline='') as webfile:
                webinfo = csv.reader(webfile)
                for row in webinfo:
                    web_rows.append(row)
            with open(csv_tot_oth, newline='') as othfile:
                othinfo = csv.reader(othfile)
                for row in othinfo:
                    oth_rows.append(row)
            for i in range(2,len(web_rows)):
                web_freqs.append(float(web_rows[i][1]))
                web_inten.append(float(web_rows[i][2]))
            for i in range(2,len(oth_rows)):
                oth_freqs.append(float(oth_rows[i][1]))
                oth_inten.append(float(oth_rows[i][2]))
            # scale "other" intensities to match scale of QQMS website csv
            max_web_inten = max(web_inten)
            max_oth_inten = max(oth_inten)
            min_web_inten = min(web_inten)
            scaled_oth_inten = []
            for i in range(0,len(oth_inten)):
                if (spect == "ir"):
                    t_inten = (-oth_inten[i])*min_web_inten/max_oth_inten + min_web_inten
                else:
                    t_inten = oth_inten[i]*max_web_inten/max_oth_inten
                scaled_oth_inten.append(t_inten)

            if (spect == "uvv"):
                xaxlab = "Wavelength (nm)"     # x axis label
                yaxlab = "Oscillator Strength (arbitrary units)" # y axis label
            else:
                xaxlab = "Frequency (cm^-1)"     # x axis label
                yaxlab = "Intensity (arbitrary units)"     # y axis label

            x1 = web_freqs
            x2 = oth_freqs
            y1 = web_inten
            y2 = scaled_oth_inten

            plt.plot(x1, y1, 'r-', label='qqms', linewidth=2)
            plt.plot(x2, y2, 'b--', label='other', linewidth=2)

#           plottitle = qmp + "_" + spect
#           plt.title(plottitle)

            plt.tick_params(axis='both',which='major',labelsize=12)
            plt.xlabel(xaxlab, size=18)
            plt.ylabel(yaxlab, size=18)
            plt.legend(loc='lower left')
            plt.tight_layout()
            pngname = qmp + "_" + spect + "_plots.png"
            plt.savefig(pngname)
          # plt.show()
            plt.close()


